name: Validate commands
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - ".claude/skills/**.md" 
permissions: read-all     
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install system requirements
      run: sudo apt-get update -y && sudo apt-get install -y dos2unix jq
    - name: Execute tests script
      run: dos2unix ci.sh; chmod +x ci.sh; bash ci.sh
